"""add language to posts

Revision ID: 182c105d94f4
Revises: 17332c35f1e1
Create Date: 2020-07-25 22:27:59.534270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182c105d94f4'
down_revision = '17332c35f1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
